services:
  - type: web
    name: jogo-biblico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    disk:
      name: jogo-biblico-disk
      mountPath: /opt/render/project/src
      sizeGB: 1